if (!require('pacman')) install.packages('pacman'); library('pacman')

# p_update(update = FALSE)  #Tells you which packages are out of date
# p_update()  #actually updates the out of date packages
#Load libraries 
# install.packages('BiocManager')
pacman::p_load("corrplot",
                  "cowplot",
               "dataRetrieval",
                  "egg",
                  "flextable",
                  "forecast",
                  "fracdiff",
                  "GGally",
                  "ggcorrplot",
                  "ggdark",
                  "ggh4x",
                  "ggmap",
                  "ggnetwork",
                  "ggnewscale",
                  "ggplot2",
                  "ggplotify",
                  "ggpubr",
                  "ggpubr",
                  "ggrepel",
                  "ggridges",
                  "ggspatial",
                  "ggthemes",
                  "ggthemes",
                  "grafify",
                  "gratia",
                  "grid",
                  "gridExtra",
                  "Hmisc",
                  "huxtable",
                  "itsadug",
               "Kendall",
                  "lavaan",
               "lme4",
                  "lubridate",
                  "magrittr",
                  "magrittr",
                  "maps",
               "mblm",
                  "mgcv",
                  "MTS",
                  "nlme",
                  "officer",
                  "patchwork",
                  "purrr",
                  "rLakeAnalyzer",
                  "rstatix",
                  "scales",
                  "scales",
                  "scam",
                  "schoenberg",
                  "segmented",
                  "semPlot",
                  "strucchange",
                  "tidyverse",
                  "tseries",
              "trend",
                  "urca",
                  "viridis",
                  "visreg",
                  "zoo",
              "zyp"
)
